export const phrases = [
  "Check one, two",
  "Check three, four",
  "Sound-checking the microphone",
  "Ahghhhhh",
  "Do ya'll wanna hear a joke?",
  "Mic check one, mic check two",
  "That's the elevator?",
  "... uhhhhh yeah um... uh...",
  "Can I get more talent in the monitors?",
  "When does catering get here?",
  "Do you really need all those lights?",
  "Man this is taking a while",
  "Where is the stage?",
  "Goodness that is a lot of stairs to get to the stage",
  "SNAKE PARTY!",
  "Where is that cable trunk?",
  "The more you point it at the loud thingy, the worse it gets okay?",
  "Production to Hospitality, where are the tissues?",
  "You patched it wrong!!!  It goes into 14 on the subsnake and 12 on the splitter!",
  "*Rachet straps* That thing ain't going no where",
  "Who is playing tonight?",
  "Mic check 1, mic check 2, mic check 3, mic check 4, mic check 1, mic check 2",
  "Mic check 9, mic check 5, Mic check pah, bah, pah, bah",
  "BINGO!  I got a piece of confetti!",
  "No you can't have a setlist",
  "You know the band?  I know the band?  Do you think that makes you special?",
];